version: '3'

services:
  api-gateway:
    build: ./api-gateway
    volumes:
      - ./api-gateway:/opt/app
    ports:
      - 5001:80
    depends_on: 
      - server
      - client
  client:
    build: ./client
    volumes:
      - ./client:/opt/app
    ports:
      - 3000:3000
  server:
    build: ./server
    volumes:
      - ./server:/opt/app
    ports:
      - 5000:5000
    